### ISSUE TITLE
confusing words

### ISSUE THREAD

**Issue by zenorogue** [Pomax/three-point-perspective#2]
I would also like to add that the use of words "cartesian" and "(non-)Euclidean" seem confusing.

(1) Euclidan is a property of geometry. The world has three-dimensional Euclidean geometry. The flat surface you are projecting it to has two-dimensional Euclidean geometry. It speaks of geometric properties of the space which do not change when you simply use another coordinate system. Projective geometry is helpful when studying projections (it is a bit different from Euclidean, but non-Euclidean is usually reserved for curved spaces). If you project the 3D world to 2D in some incorrect way, it is just a weird projection, it has nothing to do with non-Euclidean geometry.

(2) Cartesian coordinates is usually a coordinate system for the Euclidean space. So:
* in E^2 (Euclidean plane) Cartesian and polar coordinates are commonly used
* in E^3 (Euclidean space) Cartesian, cylindrical, and spherical coordinates are commonly used
* in S^2 (sphere) latitude/longitude are commonly used (though putting the sphere in E^3 and using the Cartesian coordinates from E^3 is usually simpler for computations)
* in H^2 (hyperbolic plane) e.g. Lobachevsky coordinates, Minkowski hyperboloid coordinates
So it is difficult to understand what you mean by "Cartesian but non-Euclidean", it does not seem that you are using Cartesian in the usual meaning.

**Comment by Pomax** [comment]
Good point, I think I was using Cartesian to mean "there existss a one-to-one mapping to E", and using Euclidean to mean "parallel lines stay parallel", but that's clearly not the correct use. I'll try to see if I can phrase that better for the rewrite (though if you have recommendations on which terms to use instead, I'll be more than happy to take them on board).

**Comment by Pomax** [comment]
I've completely rewritten the article and removed mention of cartesian- and euclidean-ness for now.
